---
- name: install docker CentOS
  hosts: centos
  gather_facts: no
  become: yes
  
  tasks:
    - name: install epel-release
      yum: name=epel-release state=present
    - name: install pip for docker-py
      yum: name=python-pip
    - name: install docker-py
      pip: name=docker
    - name: docker start
      command: service docker start
    - name: pull&run docker image  
      docker_container:
        name: service
        image: edowon0623/my-user-service:1.1
        detach: yes
        ports: 8088:8088

---
- name: install docker Ubuntu
  hosts: ubuntu
  gather_facts: no
  become: yes
  tasks:
    - name: apt upgrade
      apt: 
        upgrade: yes
        update_cache: yes
    - name: kernel upgrade
      apt: name='*' state=latest exclude='kernel*'
    - name: install pip for docker-py
      apt: name=python-pip
    - name: install docker-py
      pip: name=docker          
    - name: run&pull docker image  
      docker_container:
        name: service
        image: edowon0623/my-user-service:1.1
        command: run
        detach: yes
        ports: 8088:8088