
---
- name: install docker in centos
  hosts: centos
  gather_facts: no
  become: yes

  tasks:
    - name: docker install using yum
      yum: name=docker state=present
    - name: start docker
      service: name=docker state=started
    - name: image pull
      shell: docker pull edowon0623/my-user-service:1.1
    - name: container start
      shell: docker run -d -p 8088:8088 --name my-user-service docker.io/edowon0623/my-user-service:1.1


- name: install docker in ubuntu
  hosts: ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: docker install using apt
      shell: curl -s https://get.docker.com | sh
    - name: image pull
      shell: docker pull edowon0623/my-user-service:1.1
    - name: container start
      shell: docker run -d -p 8088:8088 --name my-user-service edowon0623/my-user-service:1.1
