---
- name: install docker CentOS
  hosts: centos
  gather_facts: no
  become: yes
  
  tasks:
    - name: Install docker
      shell: curl https://get.docker.com | sh
    - name: install pip for docker-py
      shell: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - name: install docker-py
      pip: name=docker
    - name: run&pull docker image  
      docker_container:
        name: service
        image: edowon0623/my-user-service:1.1
        detach: yes
        ports: 8088:8088


- name: install docker Ubuntu
  hosts: ubuntu
  gather_facts: no
  become: yes

  tasks:
    - name: Install docker
      shell: curl https://get.docker.com | sh
    - name: run&pull docker image  
      docker_container:
        name: service
        image: edowon0623/my-user-service:1.1
        detach: yes
        ports: 8088:8088