---
- name: setup for nfs server
  hosts: localhost
  gather_facts: no

  tasks:
    - name: make nfs_shared directory
      file:
        path: /home/vagrant/nfs_shared
        state: directory
        mode: 0777

    - name: configure /etc/exports
      become: yes
      lineinfile:
        path: /etc/exports
        line: /home/vagrant/nfs_shared/ 172.20.10.0/24(rw,sync)

    - name: nfs service restart
      become: yes
      service:
        name: nfs
        state: restarted


