apiVersion: v1
kindL apiVersion: v1
kind: Pod
metadata:
  name: webapl 
spec:
  containers:
  - name: werbapl
    image: 6democratickim9/webapl:0.1
    livenessProbe:
      httpGet:
        path: /healthz
        port: 3000
      initialDelaySeconds: 3
      periodseconds: 5
    readinessrobe:
      httpGet:
        path: /read
        port: 3000
      initalDelaySeconds: 15
      periodSeconds: 6
