apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-data
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data001/my-data"
