---
- name: setup for nfs server
  hosts: localhost # 로컬호스트에서 작업
  gather_facts: no 

  tasks:
    - name: make nfs_shared directory 
      file:
        path: /home/vagrant/nfs_shared # 해당 디렉토리를 만들어준다
        state: directory
        mode: 0777 # 모든 권한 허용

    - name: configure /etc/exports 
      become: yes # 루트 권한으로 실행
      lineinfile:
        path: /etc/exports 
        line: /home/vagrant/nfs_shared/ 172.20.10.0/24(rw,sync) # nfs_shared 폴더를 외부에서 사용할 수 있도록 만들 것-> 해당 ip 대역의 노드 01~03 번 노드에서 접속 가능하도록 만들 것

    - name: nfs service restart
      become: yes
      service:
        name: nfs # 서비스라는 모듈을 통해 nfs 시작
        state: restarted


