---
- name: setup for nfs clients 
  hosts: centos # 센토스 그룹에 실행예정
  gather_facts: no

  tasks:
    - name: make_nfs_client directory 
      file: 
        path: /home/vagrant/nfs # 해당 디렉토리 생성
        state: directory
    - name: mount point directory as client
      become: yes # 루트 권한으로
      mount:
        name: /home/vagrant/nfs # 생성된 디렉토리를
        src: 172.20.10.10:/home/vagrant/nfs_shared # 이 디렉토리와 공유할 예정
        fstype: nfs # 네트워크 파일 시스템으로 공유
        opts: nfsvers=3 # 공유될 서버 3대
        state: mounted # 마운트