---
- name: install nginx on centos
  hosts: centos
  gather_facts: no
  become: yes 
  tasks:
    - name: install epel-release
      yum: name=epel-release state=absent
    - name: install nginx web server
      yum: name=nginx state=present
    - name: upload default index.html for web server
      get_url: url=https://www.nginx.com dest=/usr/share/nginx/html/
    - name: start nginx web server
      service: name=nginx state=started

- name: install nginx on ubuntu
  hosts: ubuntu
  gather_facts: no
  become: yes 
  tasks:
    - name: remove nginx web server
      apt: 
        name: nginx 
        state: absent
    - name: remove useless packages from cache
      apt: 
        autoclean: yes
    - name: remove dependencies that no longer required
      apt: 
        autoremove: yes

